OnlineCourses/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineCourses.Models;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Data.Entity.Infrastructure;
using System.Data.Entity;
using System.IO;
using System.Security.Cryptography;
using System.Web.Security;

namespace OnlineCourses.Controllers
{
    public class UserManagerController : Controller
    {

        coursesDBEntities _database = new coursesDBEntities();  

        [HttpGet]
        public ActionResult Index()
        {
            Users u = _database.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name);
            Directory.CreateDirectory(Server.MapPath("~/Data/") + u.UserLogin);
            return View(u);
        }

        [HttpPost]
        public ActionResult Index(Users u)
        {

            Users user = _database.Users.FirstOrDefault(x => x.UserID == u.UserID);
            u.UserImage = user.UserImage;
            u.UserLogin = user.UserLogin;
            if (ModelState.IsValid)
            {
                if (u.UserEmail == user.UserEmail || CheckUserEmail(u.UserEmail))
                {
                    user.UserName = u.UserName;
                    user.UserEmail = u.UserEmail;
                    user.UserPhone = u.UserPhone;
                    user.UserVK = u.UserVK;

                    _database.SaveChanges();

                    return View(user);
                }
                else
                {
                    ModelState.AddModelError("EmailError", "Такой email уже привязан к другому аккаунту!");

                }
            }

            return View(u);
        }

        public bool CheckUserEmail(string email)
        {
            if (_database.Users.FirstOrDefault(x => x.UserEmail.ToLower() == email.ToLower()) == null 
               )
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        public void ChangePassword(int? u, string newPas, string newPasConfirm)
        {
            Users user = _database.Users.FirstOrDefault(x => x.UserID == u);

            if (newPas == "" && newPasConfirm == "")
            {
                ;
            }
            else if ((newPas == "" && newPasConfirm != "") || (newPas != "" && newPasConfirm != newPas)) ;
            else
            {
                var salt = System.Text.Encoding.UTF8.GetBytes("qazwsxedcrfv1029384756");
                var password = System.Text.Encoding.UTF8.GetBytes(newPas);

                var hmacMD5 = new HMACMD5(salt);
                var saltedHash = hmacMD5.ComputeHash(password);
                saltedHash = hmacMD5.ComputeHash(saltedHash);

                user.UserPassword = newPas;

                _database.SaveChanges();

            }




        }

        public ActionResult ChangeAvatar(HttpPostedFileBase upload)
        {
            Users user = _database.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name);

            if (upload != null)
            {

                if (!string.IsNullOrEmpty(upload.FileName))
                {
                    FileInfo fi = new FileInfo(upload.FileName);
                    if (fi.Extension.ToLower() == ".png" || fi.Extension.ToLower() == ".jpg" || fi.Extension.ToLower() == ".jpeg")
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Data/") + user.UserLogin + "/Users/" + user.UserLogin + "/");

                        string[] teacherFileNames = Directory.GetFiles((Server.MapPath("~/Data/") + user.UserLogin + "/Users/" + user.UserLogin + "/"));
                        foreach (string path in teacherFileNames)
                            System.IO.File.Delete(path);

                        string pathToSave_100 = Server.MapPath("~/Data/") + user.UserLogin + "/Users/" + user.UserLogin + "/" + upload.FileName;
                        upload.SaveAs(pathToSave_100);

                        pathToSave_100 = "/Data/" + user.UserLogin + "/Users/" + user.UserLogin + "/" + upload.FileName;

                        user.UserImage = pathToSave_100;
                        _database.SaveChanges();
                    }


                }


            }

            return RedirectToAction("Index");
        }

        public ActionResult DeleteAvatar()
        {
            Users user = _database.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name);

            user.UserImage = "/Images/people.png";
            Directory.CreateDirectory(Server.MapPath("~/Data/") + user.UserLogin + "/Users/" + user.UserLogin + "/");
            string[] teacherFileNames = Directory.GetFiles((Server.MapPath("~/Data/") + user.UserLogin + "/Users/" + user.UserLogin + "/"));
            foreach (string path in teacherFileNames)
                System.IO.File.Delete(path);

            _database.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Home");
        }

        

       

       
    }
}

OnlineCourses/Views/UserManager/Index.cshtml
@model OnlineCourses.Models.Users
@{
    ViewBag.Title = "Профиль";
    Layout = "~/Views/_CourseMaterialsLayout.cshtml";
}
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Профиль</h3>
        </div>

    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel" style="max-width: 383px">
                    <div class="x_title">
                        <h2>Аватар</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <img src="@Model.UserImage" style="width: 100%" />
                        <br />
                        <br />
                        @using (Html.BeginForm("ChangeAvatar", "UserManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <input type="file" name="upload" style="max-width: 100%; overflow: hidden" />
                            <br />
                            <button class="btn btn-success" onclick="location.href='@Url.Action("ChangeAvatar", "UserManager")'">Сохранить</button>
                        }
                        <button class="btn btn-danger" onclick="location.href='@Url.Action("DeleteAvatar", "UserManager")'">Удалить аватар</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-9 col-md-8 col-sm-12 col-xs-12">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Основная информация</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br>
                        @using (@Html.BeginForm("Index", "UserManager",
null,
FormMethod.Post, new { @class = "form-horizontal form-label-left", data_parsley_validate = "", novalidate = "" }))
                        {
                            @Html.HiddenFor(model => model.UserID)
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                                    ФИО<span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", required = "required" } })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                    Логин <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <span class="form-control col-md-7 col-xs-12">@Model.UserLogin</span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                    Email <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.ValidationMessage("EmailError")
                                    @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", required = "required", data_parsley_maxlength = 250 } })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                    Номер телефона
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.EditorFor(model => model.UserPhone, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", data_parsley_maxlength = 250 } })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                    Аккаунт ВКонтакте
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.EditorFor(model => model.UserVK, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", data_parsley_maxlength = 250 } })
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button type="submit" class="btn btn-success">Сохранить</button>
                                </div>
                            </div>
                        }
                        <br />
                        <form class="form-horizontal form-label-left" data-parsley-validate="" novalidate="">
                            @Html.HiddenFor(model => model.UserID)
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                    Поменять пароль
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="password" name="newPas" class="form-control col-md-7 col-xs-12" data-parsley-minlength="8" />
                                    <ul class="parsley-errors-list filled" id="parsley-id-13">
                                        <li class="parsley-minlength">@Html.ValidationMessage("FirstFieldIsEmpty")</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                    Подтвердить пароль
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="password" name="newPasConfirm" class="form-control col-md-7 col-xs-12" data-parsley-minlength="8" />
                                    <ul class="parsley-errors-list filled" id="parsley-id-13">
                                        <li class="parsley-minlength">@Html.ValidationMessage("DifferentPasswords")</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button class="btn btn-success" onclick="sendNFU(UserID.value, newPas.value, newPasConfirm.value); return false;">Изменить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>