OnlineCourses/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineCourses.Models;
using System.Web.Security;
using System.Data.Entity.Validation;
using System.IO;
using System.Security.Cryptography;

namespace OnlineCourses.Controllers
{
    public class StudentController : Controller
    {
        coursesDBEntities _database = new coursesDBEntities();


        // GET: CourseMaterials
        public ActionResult Index()
        {
            Users u = _database.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name);

            

            return View(u);
        }

        

        

        public ActionResult ViewSingleCourse(int? id)
        {
            Courses c = _database.Courses.FirstOrDefault(x => x.CourseID == id);
            return View(c);
        }

        public ActionResult ViewUnboughtCourses()
        {
            Users u = _database.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name);
            return View(u);
        }

        public ActionResult ViewSingleLesson(int? id)
        {
            Lessons l = _database.Lessons.FirstOrDefault(x => x.LessonID == id);
            Blocks block = _database.Blocks.FirstOrDefault(x => x.BlockID == l.BlockID);
            Courses course = _database.Courses.FirstOrDefault(x => x.CourseID == block.CourseID);
            Users creator = _database.Users.FirstOrDefault(x => x.UserID == course.UserID);

            Users user = _database.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name);

            Directory.CreateDirectory(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + l.LessonID + "/LessonData/");
            string[] fileNames = Directory.GetFiles(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + l.LessonID + "/LessonData/");

            ViewBag.LessonFiles = fileNames;

            foreach (Homeworks hw in l.Homeworks)
            {
                Directory.CreateDirectory(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + l.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/");
                fileNames = Directory.GetFiles(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + l.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/");

                ViewBag.HWFiles = fileNames;

                Directory.CreateDirectory(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + l.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/TeacherAnswer/");
                fileNames = Directory.GetFiles(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + l.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/TeacherAnswer/");

                ViewBag.TeacherAnswerFiles = fileNames;
            }





            return View(l);
        }

        public ActionResult DeleteHWFile(string filePath, int? id)
        {
            System.IO.File.Delete(filePath);
            return RedirectToAction("ViewSingleLesson", new { id = id }); ;
        }

        public ActionResult ViewTeacherProfile(int? id, int? lID)
        {
            ViewBag.LessonID = lID;
            Users u = _database.Users.FirstOrDefault(x => x.UserID == id);
            return View(u);
        }

        [HttpPost]
        public ActionResult UploadHWFile(int? ID)
        {

            Users user = _database.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name);
            Homeworks hw = _database.Homeworks.FirstOrDefault(x => x.HomeworkID == ID);
            UsersHomeworksTeachers hwut = _database.UsersHomeworksTeachers.FirstOrDefault(x => x.UserID == user.UserID && x.HomeworkID == hw.HomeworkID);

            if (hwut == null)
            {
                hwut = new UsersHomeworksTeachers();
                hwut.HomeworkID = hw.HomeworkID;
                hwut.UserID = user.UserID;

                _database.UsersHomeworksTeachers.Add(hwut);

                _database.SaveChanges();
            }

            Lessons lesson = _database.Lessons.FirstOrDefault(x => x.LessonID == hw.LessonID);
            Blocks block = _database.Blocks.FirstOrDefault(x => x.BlockID == lesson.BlockID);
            Courses course = _database.Courses.FirstOrDefault(x => x.CourseID == block.CourseID);
            Users creator = _database.Users.FirstOrDefault(x => x.UserID == course.UserID);

            foreach (string s in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[s];
                //  int fileSizeInBytes = file.ContentLength;
                string fileName = file.FileName;
                string fileExtension = file.ContentType;

                if (!string.IsNullOrEmpty(fileName))
                {
                    fileExtension = Path.GetExtension(fileName);
                    Directory.CreateDirectory(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/");
                    string pathToSave_100 = Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/" + file.FileName;
                    file.SaveAs(pathToSave_100);
                }

            }

            return RedirectToAction("ViewSingleLesson", new { id = lesson.LessonID }); ;

        }

        [HttpPost]
        public void UserSendsHWComment(int? uID, int? hwID, string comment)
        {
            Users user = _database.Users.FirstOrDefault(x => x.UserID == uID);
            Homeworks hw = _database.Homeworks.FirstOrDefault(x => x.HomeworkID == hwID);
            UsersHomeworksTeachers hwut = _database.UsersHomeworksTeachers.FirstOrDefault(x => x.UserID == user.UserID && x.HomeworkID == hw.HomeworkID);

            if (hwut == null)
            {
                hwut = new UsersHomeworksTeachers();
                hwut.HomeworkID = hw.HomeworkID;
                hwut.UserID = user.UserID;

                _database.UsersHomeworksTeachers.Add(hwut);

                _database.SaveChanges();
            }

            hwut.UserComment = comment;

            _database.SaveChanges();

        }

        

        public FileResult DownloadFile(string filePath)
        {
            FileInfo file = new FileInfo(filePath);
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, file.Name);
        }

        

        public ActionResult GetAccessToCourse(int? cID)
        {
            Users u = _database.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name);

            Courses c = _database.Courses.FirstOrDefault(x => x.CourseID == cID);

            u.BoughtCourses.Add(c);

            _database.SaveChanges();

            return RedirectToAction("Index");
        }

        
    }
}

OnlineCourses/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using OnlineCourses.Models;
using System.IO;
using System.Security.Cryptography;

namespace OnlineCourses.Controllers
{
    [Authorize(Roles = "user")]
    public class TeacherController : Controller
    {

        coursesDBEntities _database = new coursesDBEntities();


        

        
        public ActionResult ViewBlocks(int? id)
        {
            Courses course = _database.Courses.FirstOrDefault(x => x.CourseID == id);
            return View(course.Blocks);
        }

        public ActionResult ViewLessons(int? id)
        {
            Blocks block = _database.Blocks.FirstOrDefault(x => x.BlockID == id);
            return View(block.Lessons);
        }

        public ActionResult ViewLessonsFullPage(int? id)
        {
            Blocks block = _database.Blocks.FirstOrDefault(x => x.BlockID == id);
            return View(block.Lessons);
        }

        public ActionResult ViewHomeworks(int? id)
        {
            Lessons lesson = _database.Lessons.FirstOrDefault(x => x.LessonID == id);
            return View(lesson.Homeworks);
        }

        public ActionResult ViewHomeworksFullPage(int? id)
        {
            Lessons lesson = _database.Lessons.FirstOrDefault(x => x.LessonID == id);
            return View(lesson.Homeworks);
        }

        public ActionResult ViewHomeworksUsersTeachers(int? id)
        {
            Homeworks hw = _database.Homeworks.FirstOrDefault(x => x.HomeworkID == id);
            return View(hw.UsersHomeworksTeachers);
        }

        public ActionResult ViewHomeworksUsersTeachersFullPage(int? id)
        {
            Homeworks hw = _database.Homeworks.FirstOrDefault(x => x.HomeworkID == id);
            ViewBag.HomeworkID = hw.HomeworkID;
            return View(hw.UsersHomeworksTeachers);
        }

        public ActionResult TeacherGetsTheHW(int? teacherID, int? hwutID)
        {
            Users teahcer = _database.Users.FirstOrDefault(x => x.UserID == teacherID);
            UsersHomeworksTeachers hwut = _database.UsersHomeworksTeachers.FirstOrDefault(x => x.ID == hwutID);

            hwut.TeacherID = teahcer.UserID;
            hwut.TeacherName = teahcer.UserName;

            _database.SaveChanges();

            return RedirectToAction("ViewHomeworksUsersTeachersFullPage", new { id = hwut.HomeworkID });
        }

        public ActionResult TeacherRemoveTheHW(int? hwutID)
        {
            UsersHomeworksTeachers hwut = _database.UsersHomeworksTeachers.FirstOrDefault(x => x.ID == hwutID);
            Users user = _database.Users.FirstOrDefault(x => x.UserID == hwut.UserID);
            Homeworks hw = _database.Homeworks.FirstOrDefault(x => x.HomeworkID == hwut.HomeworkID);
            Lessons lesson = _database.Lessons.FirstOrDefault(x => x.LessonID == hw.LessonID);
            Blocks block = _database.Blocks.FirstOrDefault(x => x.BlockID == lesson.BlockID);
            Courses course = _database.Courses.FirstOrDefault(x => x.CourseID == block.CourseID);
            Users creator = _database.Users.FirstOrDefault(x => x.UserID == course.UserID);

            hwut.TeacherID = null;
            hwut.Mark = null;
            hwut.TeacherComment = null;
            hwut.TeacherName = null;

            _database.SaveChanges();

            string[] teacherFileNames = Directory.GetFiles(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/TeacherAnswer/");

            foreach (string path in teacherFileNames)
                System.IO.File.Delete(path);

            return RedirectToAction("ViewHomeworksUsersUsersFullPage", new { id = hwut.HomeworkID });
        }

        [HttpGet]
        public ActionResult CheckHW(int? hwutID)
        {
            UsersHomeworksTeachers hwut = _database.UsersHomeworksTeachers.FirstOrDefault(x => x.ID == hwutID);
            Users user = _database.Users.FirstOrDefault(x => x.UserID == hwut.UserID);
            Homeworks hw = _database.Homeworks.FirstOrDefault(x => x.HomeworkID == hwut.HomeworkID);
            Lessons lesson = _database.Lessons.FirstOrDefault(x => x.LessonID == hw.LessonID);
            Blocks block = _database.Blocks.FirstOrDefault(x => x.BlockID == lesson.BlockID);
            Courses course = _database.Courses.FirstOrDefault(x => x.CourseID == block.CourseID);
            Users creator = _database.Users.FirstOrDefault(x => x.UserID == course.UserID);

            string[] fileNames = Directory.GetFiles(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin);
            string[] teacherFileNames = Directory.GetFiles(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/TeacherAnswer/");

            ViewBag.Files = fileNames;
            ViewBag.Answers = teacherFileNames;

            return View(hwut);
        }

        [HttpGet]
        public ActionResult CheckHWFullPage(int? hwutID)
        {
            UsersHomeworksTeachers hwut = _database.UsersHomeworksTeachers.FirstOrDefault(x => x.ID == hwutID);
            Users user = _database.Users.FirstOrDefault(x => x.UserID == hwut.UserID);
            Homeworks hw = _database.Homeworks.FirstOrDefault(x => x.HomeworkID == hwut.HomeworkID);
            Lessons lesson = _database.Lessons.FirstOrDefault(x => x.LessonID == hw.LessonID);
            Blocks block = _database.Blocks.FirstOrDefault(x => x.BlockID == lesson.BlockID);
            Courses course = _database.Courses.FirstOrDefault(x => x.CourseID == block.CourseID);
            Users creator = _database.Users.FirstOrDefault(x => x.UserID == course.UserID);

            Directory.CreateDirectory(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin);
            Directory.CreateDirectory(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/TeacherAnswer/");
            string[] fileNames = Directory.GetFiles(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin);
            string[] teacherFileNames = Directory.GetFiles(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/TeacherAnswer/");

            ViewBag.Files = fileNames;
            ViewBag.Answers = teacherFileNames;

            return View(hwut);
        }

        [HttpPost]
        public ActionResult CheckHWFullPage(UsersHomeworksTeachers h)
        {
            UsersHomeworksTeachers hwut = _database.UsersHomeworksTeachers.FirstOrDefault(x => x.ID == h.ID);

           
                if (h.Mark > 0)
                    hwut.Mark = h.Mark;
                else
                    hwut.Mark = null;

                hwut.TeacherComment = h.TeacherComment;

                _database.SaveChanges();
            

            return RedirectToAction("CheckHWFullPage", new { hwutID = hwut.ID });
        }

        public FileResult DownloadFile(string filePath)
        {
            FileInfo file = new FileInfo(filePath);
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, file.Name);
        }

        public ActionResult DeleteFile(string filePath, int? hwutID)
        {
            System.IO.File.Delete(filePath);
            return RedirectToAction("CheckHWFullPage", new { hwutID = hwutID }); ;
        }

        [HttpPost]
        public ActionResult UploadFile(int? ID)
        {
            UsersHomeworksTeachers hwut = _database.UsersHomeworksTeachers.FirstOrDefault(x => x.ID == ID);
            Users user = _database.Users.FirstOrDefault(x => x.UserID == hwut.UserID);
            Homeworks hw = _database.Homeworks.FirstOrDefault(x => x.HomeworkID == hwut.HomeworkID);
            Lessons lesson = _database.Lessons.FirstOrDefault(x => x.LessonID == hw.LessonID);
            Blocks block = _database.Blocks.FirstOrDefault(x => x.BlockID == lesson.BlockID);
            Courses course = _database.Courses.FirstOrDefault(x => x.CourseID == block.CourseID);
            Users creator = _database.Users.FirstOrDefault(x => x.UserID == course.UserID);

            foreach (string s in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[s];
                //  int fileSizeInBytes = file.ContentLength;
                string fileName = file.FileName;
                string fileExtension = file.ContentType;

                if (!string.IsNullOrEmpty(fileName))
                {
                    fileExtension = Path.GetExtension(fileName);
                    Directory.CreateDirectory(Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/TeacherAnswer/");
                    string pathToSave_100 = Server.MapPath("~/Data/") + creator.UserLogin + "/" + course.CourseID + "/" + block.BlockID + "/" + lesson.LessonID + "/" + hw.HomeworkID + "/" + user.UserLogin + "/TeacherAnswer/" + file.FileName;
                    file.SaveAs(pathToSave_100);
                }

            }

            return RedirectToAction("CheckHWFullPage", new { hwutID = ID });
            
        }

        [HttpGet]
        public ActionResult CreateCourse()
        {

OnlineCourses/Views/_CourseMaterialsLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap -->
    <link href="~/Gentelella/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/Gentelella/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/Gentelella/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/Gentelella/vendors/iCheck/skins/flat/green.css" rel="stylesheet">


    <!-- bootstrap-datetimepicker -->
    <link href="~/Gentelella/vendors/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css" rel="stylesheet">
    
    <link href="~/Gentelella/vendors/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" rel="stylesheet">

    <link href="~/Gentelella/vendors/dropzone/dist/min/dropzone.min.css" rel="stylesheet">
    <link href="~/Gentelella/vendors/pnotify/dist/pnotify.css" rel="stylesheet" />
    <link href="~/Gentelella/vendors/pnotify/dist/pnotify.buttons.css" rel="stylesheet" />
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <link href="~/Gentelella/build/css/custom.css" rel="stylesheet" />
</head>

<body class="nav-md cmBody" style="background: #2A3F54">
    @using (OnlineCourses.Models.coursesDBEntities _db = new OnlineCourses.Models.coursesDBEntities())
    {
        var user = _db.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name);

        <div class="container body">
            <div class="main_container">


                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view" style="background: #2A3F54">

                        <div class="clearfix"></div>
                        <!-- menu profile quick info -->
                        <div class="profile clearfix">
                            <div class="profile_pic">
                                <img src="@user.UserImage" class="img-circle profile_img" />
                            </div>
                            <div class="profile_info">
                                <span>Привет,</span>
                                <h2>@user.UserName</h2>
                            </div>
                        </div>
                        <!-- /menu profile quick info -->
                        <br />
                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            <div class="menu_section">
                                <h3>Основное</h3>
                                <ul class="nav side-menu">
                                    <li>
                                        <a href="@Url.Action("Index", "UserManager")"><i class="fa fa-home"></i> Профиль </a>
                                    </li>
                                    <li>
                                        <a><i class="fa fa-book"></i> Студент <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="@Url.Action("Index", "Student")">Купленные курсы</a></li>
                                            <li><a href="@Url.Action("ViewUnboughtCourses", "Student")">Новые курсы</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a><i class="fa fa-book"></i> Учитель <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li>
                                                <a style="font-weight:700">Работа с курсами</a>
                                                <ul class="nav child_menu">


                                                    <li><a href="@Url.Action("CreateCourse", "Teacher")" style="font-weight:700">НОВЫЙ КУРС</a></li>

                                                    @foreach (OnlineCourses.Models.Courses c in _db.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name).MyCourses)
                                                    {
                                                        <li><a href="@Url.Action("EditCourse", "Teacher", new { id = c.CourseID })">@c.CourseName</a></li>
                                                    }




                                                </ul>
                                            </li>
                                            <li>
                                                <a style="font-weight:700">Проверка домашних заданий</a>
                                                <ul class="nav child_menu">




                                                    @foreach (OnlineCourses.Models.Courses c in _db.Users.FirstOrDefault(x => x.UserLogin == User.Identity.Name).MyCourses)
                                                    {
                                                        <li><a href="@Url.Action("ViewBlocks", "Teacher", new { id = c.CourseID })">@c.CourseName</a></li>
                                                    }




                                                </ul>
                                            </li>





                                        </ul>
                                    </li>

                                </ul>

                            </div>

                        </div>
                        <!-- /sidebar menu -->
                        <!-- /menu footer buttons -->
                        <!-- /menu footer buttons -->
                    </div>
                </div>
                <!-- top navigation -->
                <div class="top_nav">
                    <div class="nav_menu">
                        <nav>
                            <div class="nav toggle">
                                <a id="menu_toggle"><i class="fa fa-bars" style="color: #2A3F54"></i></a>
                            </div>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="">
                                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <img src="@user.UserImage" />@user.UserName
                                        <span class="fa fa-angle-down"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                                        <li><a href="@Url.Action("LogOut", "UserManager")"><i class="fa fa-sign-out pull-right"></i> Выйти</a></li>
                                    </ul>
                                </li>

                            </ul>
                        </nav>
                    </div>
                </div>
                <!-- /top navigation -->
                <!-- page content -->
                <div class="right_col" role="main">
                    @RenderBody()
                </div>
                <!-- /page content -->
                <!-- footer content -->
                <footer>
                    <div class="pull-right">
                        &copy; <a href="http://inc.styleru.net/">STYLERU INC</a>
                    </div>
                    <div class="clearfix"></div>
                </footer>
                <!-- /footer content -->
            </div>
        </div>
    }
    <!-- jQuery -->
    <script src="~/Gentelella/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Gentelella/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/Gentelella/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/Gentelella/vendors/nprogress/nprogress.js"></script>
    <!-- iCheck -->
    <script src="~/Gentelella/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <!-- Datatables -->
    <script src="~/Gentelella/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="~/Gentelella/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="~/Gentelella/vendors/jszip/dist/jszip.min.js"></script>

    <script src="~/Gentelella/vendors/moment/min/moment.min.js"></script>
    <script src="~/Gentelella/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap-datetimepicker -->

    <script src="~/Gentelella/vendors/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Gentelella/vendors/parsleyjs/dist/parsley.js"></script>
    <script src="~/Gentelella/vendors/parsleyjs/dist/i18n/ru.js"></script>
    <script src="~/Gentelella/vendors/dropzone/dist/dropzone.js"></script>
    <script src="~/Gentelella/vendors/jquery-knob/js/jquery.knob.js"></script>
    <script src="~/Scripts/moment.min.js"></script>

    <script src="~/Scripts/toastr.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="~/Gentelella/build/js/custom.js"></script>

    <script>
        $('#myDatepicker').datetimepicker({
            format: 'DD.MM.YYYY HH:mm'
        });
        $('#myDatepicker2').datetimepicker({
            format: 'HH:mm'
        });
        $('#myDatepicker3').datetimepicker({
            format: 'MM.YYYY'
        });
    </script>

</body>
</html>